# Logistic (regression) classifier: Tensorflow

In [54]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

In [4]:
import numpy as np

In [5]:
xy = np.loadtxt('diabetes.csv', delimiter=',', dtype=np.float32)

In [6]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

#Placeholders for a tensor that will be always fed.

X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

In [7]:
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

#Accuracy computation
#True if hypothsis > 0.5, else fALSE

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [9]:
#Launch Graph

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    feed = {X: x_data, Y: y_data}
    for step in range(10001):
        sess.run(train, feed_dict=feed)
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict=feed))
            
    #Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict=feed)
    print('\n Hypothesis: ', h, '\n Correct (Y): ', c, '\n Accuracy: ', a)

0 nan
200 nan
400 nan
600 nan
800 nan
1000 nan
1200 nan
1400 nan
1600 nan
1800 nan
2000 nan
2200 nan
2400 nan
2600 nan
2800 nan
3000 nan
3200 nan
3400 nan
3600 nan
3800 nan
4000 nan
4200 nan
4400 nan
4600 nan
4800 nan
5000 nan
5200 nan
5400 nan
5600 nan
5800 nan
6000 nan
6200 nan
6400 nan
6600 nan
6800 nan
7000 nan
7200 nan
7400 nan
7600 nan
7800 nan
8000 nan
8200 nan
8400 nan
8600 nan
8800 nan
9000 nan
9200 nan
9400 nan
9600 nan
9800 nan
10000 nan

 Hypothesis:  [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]


In [35]:
def MinMaxScaler(data):
    numerator = data - np.mean(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

x_data = MinMaxScaler(x_data)

In [11]:
#Placeholders for a tensor that will be always fed.

X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

In [12]:
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

#Accuracy computation
#True if hypothsis > 0.5, else fALSE

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [15]:
#Launch Graph

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    feed = {X: x_data, Y: y_data}
    
    for step in range(20001):
        sess.run(train, feed_dict=feed)
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict=feed))
            
    #Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict=feed)
    print('\n Hypothesis: ', h, '\n Correct (Y): ', c, '\n Accuracy: ', a)

0 0.67066884
200 0.66562724
400 0.66083986
600 0.65624374
800 0.6518092
1000 0.6475206
1200 0.6433688
1400 0.63934743
1600 0.6354514
1800 0.63167614
2000 0.62801754
2200 0.6244716
2400 0.6210346
2600 0.6177028
2800 0.6144726
3000 0.61134076
3200 0.60830384
3400 0.60535854
3600 0.60250187
3800 0.5997309
4000 0.59704244
4200 0.59443384
4400 0.5919025
4600 0.58944553
4800 0.5870605
5000 0.584745
5200 0.58249646
5400 0.5803128
5600 0.5781916
5800 0.57613087
6000 0.57412845
6200 0.57218236
6400 0.5702906
6600 0.56845146
6800 0.5666631
7000 0.5649237
7200 0.56323165
7400 0.56158537
7600 0.5599832
7800 0.5584238
8000 0.5569057
8200 0.5554274
8400 0.55398756
8600 0.55258507
8800 0.55121857
9000 0.5498869
9200 0.5485888
9400 0.5473234
9600 0.54608935
9800 0.5448858
10000 0.5437118
10200 0.54256624
10400 0.5414483
10600 0.5403571
10800 0.53929174
11000 0.53825146
11200 0.53723544
11400 0.5362429
11600 0.5352731
11800 0.53432536
12000 0.533399
12200 0.5324934
12400 0.53160787
12600 0.5307419
1280

# Softmax classification

In [20]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 200 == 0:
                print(step, cost_val)

0 1.5866632
200 0.70099527
400 0.59057564
600 0.49806285
800 0.4085543
1000 0.31897604
1200 0.24187851
1400 0.21791509
1600 0.19906487
1800 0.1830743
2000 0.1693553


In [22]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

'''
(101, 16) (101, 1)
'''

nb_classes = 7  # 0 ~ 6

X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])  # 0 ~ 6


(101, 16) (101, 1)


In [23]:
Y_one_hot = tf.one_hot(Y, nb_classes)  # one hot
print("one_hot:", Y_one_hot)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print("reshape one_hot:", Y_one_hot)

'''
one_hot: Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)
reshape one_hot: Tensor("Reshape:0", shape=(?, 7), dtype=float32)
'''

W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

one_hot: Tensor("one_hot_1:0", shape=(None, 1, 7), dtype=float32)
reshape one_hot: Tensor("Reshape_1:0", shape=(None, 7), dtype=float32)


In [24]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

# Cross entropy cost/loss
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,
                                                                 labels=tf.stop_gradient([Y_one_hot])))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [25]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        _, cost_val, acc_val = sess.run([optimizer, cost, accuracy], feed_dict={X: x_data, Y: y_data})
                                        
        if step % 100 == 0:
            print("Step: {:5}\tCost: {:.3f}\tAcc: {:.2%}".format(step, cost_val, acc_val))

    # Let's see if we can predict
    pred = sess.run(prediction, feed_dict={X: x_data})
    # y_data: (N,1) = flatten => (N, ) matches pred.shape
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))


Step:     0	Cost: 6.183	Acc: 15.84%
Step:   100	Cost: 0.725	Acc: 86.14%
Step:   200	Cost: 0.458	Acc: 90.10%
Step:   300	Cost: 0.348	Acc: 90.10%
Step:   400	Cost: 0.279	Acc: 94.06%
Step:   500	Cost: 0.232	Acc: 94.06%
Step:   600	Cost: 0.199	Acc: 94.06%
Step:   700	Cost: 0.173	Acc: 95.05%
Step:   800	Cost: 0.153	Acc: 97.03%
Step:   900	Cost: 0.138	Acc: 98.02%
Step:  1000	Cost: 0.124	Acc: 98.02%
Step:  1100	Cost: 0.114	Acc: 98.02%
Step:  1200	Cost: 0.104	Acc: 98.02%
Step:  1300	Cost: 0.096	Acc: 99.01%
Step:  1400	Cost: 0.089	Acc: 99.01%
Step:  1500	Cost: 0.083	Acc: 99.01%
Step:  1600	Cost: 0.078	Acc: 99.01%
Step:  1700	Cost: 0.073	Acc: 99.01%
Step:  1800	Cost: 0.069	Acc: 100.00%
Step:  1900	Cost: 0.065	Acc: 100.00%
Step:  2000	Cost: 0.062	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 Tru

# Datasets: tensorflow

In [26]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]


In [27]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [28]:
# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 6.3002696 [[ 0.5666105   1.7702644   0.9448427 ]
 [-1.1833189  -1.0453693  -0.45675272]
 [ 0.82325035 -1.1157026   0.97933495]]
1 4.3315525 [[ 0.5786585   1.807474    0.89558506]
 [-1.0541725  -0.87097436 -0.76029396]
 [ 0.9485921  -0.9285184   0.6668089 ]]
2 3.3154461 [[ 0.52845436  1.8442533   0.90900993]
 [-1.2153902  -0.69753987 -0.77251077]
 [ 0.7773819  -0.7418711   0.6513718 ]]
3 2.3522854 [[ 0.5107834   1.8796526   0.89128155]
 [-1.2094601  -0.5274408  -0.9485399 ]
 [ 0.76753783 -0.55724746  0.47659224]]
4 1.6112276 [[ 0.46307632  1.9114046   0.9072366 ]
 [-1.367305   -0.36962146 -0.94851434]
 [ 0.5970584  -0.3813647   0.4711889 ]]
5 1.4660379 [[ 0.4542857   1.9255699   0.90186185]
 [-1.328568   -0.29801154 -1.0588613 ]
 [ 0.6148558  -0.2771809   0.3492077 ]]
6 1.4208002 [[ 0.4378761   1.9187871   0.9250542 ]
 [-1.3241907  -0.34313193 -1.0181181 ]
 [ 0.5908889  -0.27937546  0.3753692 ]]
7 1.3989806 [[ 0.42339507  1.9175317   0.9407906 ]
 [-1.3129497  -0.35795903 -1.0145321 ]


## Too big learning rate

In [29]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 10.503568 [[ 2.1473308  -1.8104824   0.9891026 ]
 [ 1.4515973  -0.7766717  -1.526612  ]
 [ 0.7292234   0.15615118 -0.7374763 ]]
1 20.505472 [[ 1.0224875  -1.2480373   1.5515008 ]
 [-2.6730843   1.8482146  -0.02681684]
 [-3.3955927   2.9685717   0.5749195 ]]
2 21.695984 [[ 1.3974874  -2.176369    2.1048326 ]
 [-0.2355845  -2.0708146   1.4547127 ]
 [-0.9580927  -0.77212095  1.8781126 ]]
3 12.32185 [[ 1.7724773 -1.613869   1.1673429]
 [ 2.201895   0.5541854 -3.6077666]
 [ 1.479397   2.040379  -3.3718774]]
4 inf [[ 0.6637833 -1.067675   1.7298429]
 [-1.8880174  3.144098  -2.1077666]
 [-2.572727   4.7800026 -2.0593774]]
5 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
6 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
7 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
8 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
9 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
10 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
11 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
12 nan [[

## Too small learning rate

In [30]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 3.484027 [[-0.24705672 -1.152827    0.40111333]
 [-0.14268851 -0.82493734 -0.7828744 ]
 [ 1.337713    0.25510642 -0.80939215]]
1 3.484027 [[-0.24705672 -1.152827    0.40111333]
 [-0.14268851 -0.82493734 -0.7828744 ]
 [ 1.337713    0.25510642 -0.80939215]]
2 3.484027 [[-0.24705672 -1.152827    0.40111333]
 [-0.14268851 -0.82493734 -0.7828744 ]
 [ 1.337713    0.25510642 -0.80939215]]
3 3.484027 [[-0.24705672 -1.152827    0.40111333]
 [-0.14268851 -0.82493734 -0.7828744 ]
 [ 1.337713    0.25510642 -0.80939215]]
4 3.484027 [[-0.24705672 -1.152827    0.40111333]
 [-0.14268851 -0.82493734 -0.7828744 ]
 [ 1.337713    0.25510642 -0.80939215]]
5 3.484027 [[-0.24705672 -1.152827    0.40111333]
 [-0.14268851 -0.82493734 -0.7828744 ]
 [ 1.337713    0.25510642 -0.80939215]]
6 3.484027 [[-0.24705672 -1.152827    0.40111333]
 [-0.14268851 -0.82493734 -0.7828744 ]
 [ 1.337713    0.25510642 -0.80939215]]
7 3.484027 [[-0.24705672 -1.152827    0.40111333]
 [-0.14268851 -0.82493734 -0.7828744 ]
 [ 1.337

# Non-normalized inputs

In [31]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]


In [32]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [33]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  11951182000.0 
Prediction:
 [[ 77838.516]
 [156191.55 ]
 [122972.71 ]
 [ 86348.305]
 [101678.74 ]
 [102531.39 ]
 [ 94009.16 ]
 [119565.17 ]]
1 Cost:  1.3130525e+25 
Prediction:
 [[-2.5560678e+12]
 [-5.1456267e+12]
 [-4.0478785e+12]
 [-2.8375413e+12]
 [-3.3441941e+12]
 [-3.3723415e+12]
 [-3.0908678e+12]
 [-3.9352890e+12]]
2 Cost:  inf 
Prediction:
 [[8.4724320e+19]
 [1.7055874e+20]
 [1.3417241e+20]
 [9.4054151e+19]
 [1.1084784e+20]
 [1.1178082e+20]
 [1.0245100e+20]
 [1.3044048e+20]]
3 Cost:  inf 
Prediction:
 [[-2.8083022e+27]
 [-5.6534005e+27]
 [-4.4473261e+27]
 [-3.1175520e+27]
 [-3.6742015e+27]
 [-3.7051265e+27]
 [-3.3958768e+27]
 [-4.3236261e+27]]
4 Cost:  inf 
Prediction:
 [[9.3084970e+34]
 [1.8738958e+35]
 [1.4741262e+35]
 [1.0333547e+35]
 [1.2178637e+35]
 [1.2281143e+35]
 [1.1256091e+35]
 [1.4331242e+35]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]


# Normalized inputs

In [37]:
xy = MinMaxScaler(xy)
print(xy)

[[ 0.53590045  0.56875715 -0.38043478  0.49104821  0.49485275]
 [ 0.24138537  0.27315268  0.61956522  0.20986603  0.33241067]
 [ 0.08002594  0.07150539  0.19565217  0.09751621  0.15548585]
 [-0.12519602 -0.11756261 -0.27173913 -0.04906045 -0.06713806]
 [ 0.05026046 -0.00541895 -0.07608696  0.07609626 -0.07890323]
 [ 0.03146225 -0.00541895 -0.06521739 -0.02764045 -0.01238587]
 [-0.3497389  -0.43124285 -0.17391304 -0.28887403 -0.31917486]
 [-0.46409954 -0.35377185  0.15217391 -0.50895179 -0.50514724]]


In [38]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  675365.75 
Prediction:
 [[-1.944734  ]
 [-0.05629671]
 [-0.72870636]
 [-1.4599569 ]
 [-1.1954621 ]
 [-1.2043751 ]
 [-1.2077823 ]
 [-0.6355804 ]]
1 Cost:  675338.75 
Prediction:
 [[-1.9282357 ]
 [-0.03983277]
 [-0.7122612 ]
 [-1.443533  ]
 [-1.179022  ]
 [-1.1879396 ]
 [-1.1913888 ]
 [-0.6191969 ]]
2 Cost:  675311.75 
Prediction:
 [[-1.9117374 ]
 [-0.02336913]
 [-0.69581616]
 [-1.4271091 ]
 [-1.1625819 ]
 [-1.1715044 ]
 [-1.1749957 ]
 [-0.60281366]]
3 Cost:  675284.75 
Prediction:
 [[-1.8952398 ]
 [-0.00690603]
 [-0.6793716 ]
 [-1.4106857 ]
 [-1.1461424 ]
 [-1.1550695 ]
 [-1.1586027 ]
 [-0.5864308 ]]
4 Cost:  675257.75 
Prediction:
 [[-1.8787425 ]
 [ 0.00955695]
 [-0.6629273 ]
 [-1.3942626 ]
 [-1.129703  ]
 [-1.1386349 ]
 [-1.1422102 ]
 [-0.57004833]]
5 Cost:  675230.7 
Prediction:
 [[-1.8622456 ]
 [ 0.02601951]
 [-0.64648336]
 [-1.3778398 ]
 [-1.1132641 ]
 [-1.1222007 ]
 [-1.125818  ]
 [-0.55366606]]
6 Cost:  675203.75 
Prediction:
 [[-1.8457487 ]
 [ 0.04248184]
 [-0.63003975]