## Linear regression: Tensorflow

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

import matplotlib.pyplot as plt

In [3]:
X = [1, 2, 3]
Y = [1, 2, 3]

W = tf.placeholder(tf.float32)

#Our hypothesis for linear model X*W
hypothesis = X*W

In [9]:
#cost / Loss Function

cost = tf.reduce_mean(tf.square(hypothesis - Y))

#Launch the graph in a session.
W_history = []
cost_history = []

#Initializes global variables in the graph.
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    #Variables for plotting cost function
    for i in range(-30, 50):
        curr_W = i*0.1
        curr_cost = sess.run(cost, feed_dict={W: curr_W})
        W_history.append(curr_W)
        cost_history.append(curr_cost)
    

In [10]:
#Show the cost function
plt.plot(W_history, cost_history)
plt.show()

In [13]:
x_data = [1,2,3]
y_data = [1,2,3]

W = tf.Variable(tf.random_normal([1]), name='weight')
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

#Our hypothesis for linear model X*W

hypothesis = X*W

cost = tf.reduce_sum(tf.square(hypothesis - Y))

#Minimize: Gradient Descent using derivative: W -= Learning_rate * derivative
learning_rate = 0.1
gradient = tf.reduce_mean((W*X - Y) * X)
descent = W - learning_rate * gradient
update = W.assign(descent)

#Launch the graph in a session.
with tf.Session() as sess:
    #Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())
    
    for step in range(21):
        _, cost_val, W_val = sess.run(
        [update, cost, W], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

0 0.29886883 [1.1461087]
1 0.08501137 [1.0779246]
2 0.024181085 [1.0415598]
3 0.0068781166 [1.0221652]
4 0.001956442 [1.0118214]
5 0.0005564966 [1.0063047]
6 0.00015829071 [1.0033625]
7 4.5027195e-05 [1.0017934]
8 1.2805561e-05 [1.0009564]
9 3.642414e-06 [1.0005101]
10 1.0360471e-06 [1.000272]
11 2.9476934e-07 [1.0001451]
12 8.385412e-08 [1.0000774]
13 2.3817734e-08 [1.0000412]
14 6.8249193e-09 [1.000022]
15 1.9415012e-09 [1.0000118]
16 5.6338934e-10 [1.0000063]
17 1.5597834e-10 [1.0000033]
18 4.3499426e-11 [1.0000018]
19 1.2732926e-11 [1.000001]
20 3.1832315e-12 [1.0000005]


In [17]:
X = [1,2,3]
Y = [1,2,3]

#Set wrong model weights

W = tf.Variable(5.0)


#Our hypothesis for linear model X*W

hypothesis = X*W

cost = tf.reduce_mean(tf.square(hypothesis - Y))

#Minimize: Gradient Descent Magic
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

#Launch the graph in a session.
with tf.Session() as sess:
    #Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, W_val = sess.run([train, W])
        print(step, W_val)

0 5.0
1 1.2666664
2 1.0177778
3 1.0011852
4 1.000079
5 1.0000052
6 1.0000004
7 1.0
8 1.0
9 1.0
10 1.0
11 1.0
12 1.0
13 1.0
14 1.0
15 1.0
16 1.0
17 1.0
18 1.0
19 1.0
20 1.0
21 1.0
22 1.0
23 1.0
24 1.0
25 1.0
26 1.0
27 1.0
28 1.0
29 1.0
30 1.0
31 1.0
32 1.0
33 1.0
34 1.0
35 1.0
36 1.0
37 1.0
38 1.0
39 1.0
40 1.0
41 1.0
42 1.0
43 1.0
44 1.0
45 1.0
46 1.0
47 1.0
48 1.0
49 1.0
50 1.0
51 1.0
52 1.0
53 1.0
54 1.0
55 1.0
56 1.0
57 1.0
58 1.0
59 1.0
60 1.0
61 1.0
62 1.0
63 1.0
64 1.0
65 1.0
66 1.0
67 1.0
68 1.0
69 1.0
70 1.0
71 1.0
72 1.0
73 1.0
74 1.0
75 1.0
76 1.0
77 1.0
78 1.0
79 1.0
80 1.0
81 1.0
82 1.0
83 1.0
84 1.0
85 1.0
86 1.0
87 1.0
88 1.0
89 1.0
90 1.0
91 1.0
92 1.0
93 1.0
94 1.0
95 1.0
96 1.0
97 1.0
98 1.0
99 1.0


In [18]:
X = [1,2,3]
Y = [1,2,3]

#Set wrong model weights

W = tf.Variable(-3.0)


#Our hypothesis for linear model X*W

hypothesis = X*W

cost = tf.reduce_mean(tf.square(hypothesis - Y))

#Minimize: Gradient Descent Magic
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

#Launch the graph in a session.
with tf.Session() as sess:
    #Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, W_val = sess.run([train, W])
        print(step, W_val)

0 -3.0
1 0.7333336
2 0.98222226
3 0.9988148
4 0.99992096
5 0.9999947
6 0.99999964
7 0.99999994
8 1.0
9 1.0
10 1.0
11 1.0
12 1.0
13 1.0
14 1.0
15 1.0
16 1.0
17 1.0
18 1.0
19 1.0
20 1.0
21 1.0
22 1.0
23 1.0
24 1.0
25 1.0
26 1.0
27 1.0
28 1.0
29 1.0
30 1.0
31 1.0
32 1.0
33 1.0
34 1.0
35 1.0
36 1.0
37 1.0
38 1.0
39 1.0
40 1.0
41 1.0
42 1.0
43 1.0
44 1.0
45 1.0
46 1.0
47 1.0
48 1.0
49 1.0
50 1.0
51 1.0
52 1.0
53 1.0
54 1.0
55 1.0
56 1.0
57 1.0
58 1.0
59 1.0
60 1.0
61 1.0
62 1.0
63 1.0
64 1.0
65 1.0
66 1.0
67 1.0
68 1.0
69 1.0
70 1.0
71 1.0
72 1.0
73 1.0
74 1.0
75 1.0
76 1.0
77 1.0
78 1.0
79 1.0
80 1.0
81 1.0
82 1.0
83 1.0
84 1.0
85 1.0
86 1.0
87 1.0
88 1.0
89 1.0
90 1.0
91 1.0
92 1.0
93 1.0
94 1.0
95 1.0
96 1.0
97 1.0
98 1.0
99 1.0


## Linear Regression with multiple variables: Tensorflow

In [5]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  12060.22 
Prediction:
 [50.669353 69.86575  64.07901  69.99647  55.612854]
10 Cost:  5.702905 
Prediction:
 [147.80356 186.59662 179.10487 195.25566 144.64574]
20 Cost:  5.5631804 
Prediction:
 [148.1065  186.94359 179.45569 195.63658 144.90701]
30 Cost:  5.5339537 
Prediction:
 [148.11649 186.93845 179.45952 195.63966 144.89975]
40 Cost:  5.5049 
Prediction:
 [148.12553 186.93225 179.46233 195.64162 144.8917 ]
50 Cost:  5.4760246 
Prediction:
 [148.13455 186.92609 179.4651  195.64354 144.88365]
60 Cost:  5.447263 
Prediction:
 [148.14355 186.9199  179.46785 195.64546 144.87563]
70 Cost:  5.4187174 
Prediction:
 [148.15251 186.91377 179.47061 195.64738 144.86763]
80 Cost:  5.390253 
Prediction:
 [148.16147 186.90764 179.47336 195.64929 144.85963]
90 Cost:  5.361975 
Prediction:
 [148.1704  186.90152 179.4761  195.65121 144.85168]
100 Cost:  5.3338766 
Prediction:
 [148.17929 186.89545 179.47885 195.6531  144.84375]
110 Cost:  5.305913 
Prediction:
 [148.18817 186.88937 179.481

In [8]:
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  124015.98 
Prediction:
 [[-159.55382]
 [-192.10225]
 [-189.361  ]
 [-204.54565]
 [-147.73027]]
10 Cost:  5.1738763 
Prediction:
 [[151.96071]
 [182.32648]
 [179.56407]
 [197.2046 ]
 [137.86732]]
20 Cost:  4.0237627 
Prediction:
 [[152.89719]
 [183.46356]
 [180.67853]
 [198.41833]
 [138.73741]]
30 Cost:  4.0089846 
Prediction:
 [[152.894  ]
 [183.47119]
 [180.68011]
 [198.42018]
 [138.74599]]
40 Cost:  3.9943116 
Prediction:
 [[152.88799]
 [183.47537]
 [180.67834]
 [198.41837]
 [138.75194]]
50 Cost:  3.9796822 
Prediction:
 [[152.88197]
 [183.47955]
 [180.67657]
 [198.41653]
 [138.75787]]
60 Cost:  3.9651642 
Prediction:
 [[152.87598]
 [183.4837 ]
 [180.6748 ]
 [198.41473]
 [138.7638 ]]
70 Cost:  3.9507327 
Prediction:
 [[152.87001]
 [183.48787]
 [180.67307]
 [198.41293]
 [138.76968]]
80 Cost:  3.9363105 
Prediction:
 [[152.86403]
 [183.492  ]
 [180.67128]
 [198.4111 ]
 [138.77557]]
90 Cost:  3.9220123 
Prediction:
 [[152.8581 ]
 [183.49612]
 [180.66954]
 [198.4093 ]
 [138.7814