In [7]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()

In [3]:
import numpy as np

# Simple 1D array and slicing


In [1]:
import pprint as pp

In [5]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


# 2D Array

In [6]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


## Tensor Manipulation

In [8]:
sess = tf.Session()
t = tf.constant([1,2,3,4])
tf.shape(t).eval(session=sess)

array([4])

In [9]:
t = tf.constant([[1,2],
                 [3,4]])

tf.shape(t).eval(session=sess)

array([2, 2])

In [7]:
t = tf.constant([[[[1,2,3,4], [5,6,7,8], [9,10,11,12]],
                  [[13,14,15,16], [17,18,19,20], [21,22,23,24]]]])
tf.shape(t).eval(session=sess)

array([1, 2, 3, 4])

# Shape, Rank, Axis

In [10]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval(session=sess)

array([1, 2, 3, 4])

# Matmul vs multiply

In [8]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])

print('Metrix 1 shape', matrix1.shape)
print('Metrix 2 shape', matrix2.shape)

tf.matmul(matrix1, matrix2).eval(session=sess)

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [15]:
(matrix1 * matrix2).eval(session=sess)

array([[1., 2.],
       [6., 8.]], dtype=float32)

행렬곱 -> matmul 사용

## Reduce mean

In [10]:
tf.reduce_mean([1,2], axis=0).eval(session=sess)

1

In [11]:
x = [[1., 2.],
    [3., 4.]]

tf.reduce_mean(x).eval(session=sess)

2.5

In [12]:
tf.reduce_mean(x, axis=0).eval(session=sess)

array([2., 3.], dtype=float32)

In [13]:
tf.reduce_mean(x, axis=1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

In [14]:
tf.reduce_mean(x, axis=-1).eval(session=sess)

array([1.5, 3.5], dtype=float32)

#### axis=0 -> column기준 계산
#### axis=1 -> row 기준 계산

## Reduce Sum

In [16]:
tf.reduce_sum(x).eval(session=sess)

10.0

In [17]:
tf.reduce_sum(x, axis=0).eval(session=sess)

array([4., 6.], dtype=float32)

In [18]:
tf.reduce_sum(x, axis=-1).eval(session=sess)

array([3., 7.], dtype=float32)

In [20]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval(session=sess)

5.0

## Argmax

최댓값의 위치

In [21]:
x = [[0,1,2],
     [2,1,0]]

tf.argmax(x, axis=0).eval(session=sess)

array([1, 0, 0], dtype=int64)

In [22]:
tf.argmax(x, axis=1).eval(session=sess)

array([2, 0], dtype=int64)

In [23]:
tf.argmax(x, axis=-1).eval(session=sess)

array([2, 0], dtype=int64)

## Reshape

In [29]:
t = np.array([[[0,1,2],
               [3,4,5]],
            
            [[6,7,8],
            [9,10,11]]])

t.shape

(2, 2, 3)

In [31]:
tf.reshape(t, shape=[-1, 3]).eval(session=sess)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
tf.reshape(t, shape=[-1, 1, 3]).eval(session=sess)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

## One hot

In [33]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval(session=sess)

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

깊이가 3인 block을 생각. 3칸의 블럭에서 0, 1, 2, 0번째 블럭에 색칠된 값

In [34]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval(session=sess)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

# Casting

강제로 형태 변환

In [12]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(session=sess)

array([1, 2, 3, 4])

In [13]:
tf.cast([True, False, 1==1, 0==1], tf.int32).eval(session=sess)

array([1, 0, 1, 0])

# Stack

In [14]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

#Pack along first dim.
tf.stack([x,y,z]).eval(session=sess)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
tf.stack([x, y, z], axis=1).eval(session=sess)

array([[1, 2, 3],
       [4, 5, 6]])

# Ones and Zeros like

In [18]:
x = [[0, 1, 2],
     [2 ,1, 0]]

tf.ones_like(x).eval(session=sess)

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
tf.zeros_like(x).eval(session=sess)

array([[0, 0, 0],
       [0, 0, 0]])

# Zip

In [20]:
for x, y in zip([1,2,3], [4,5,6]):
    print(x, y)

1 4
2 5
3 6


In [21]:
for x, y, z in zip([1,2,3], [4,5,6], [7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
